//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTCSohbet
    {
        public int Sohbet_No { get; set; }
        public Nullable<int> kullanici_no { get; set; }
        public string kullanici_mesaj { get; set; }
        public Nullable<System.DateTime> gönderim_tarih { get; set; }
    
        public virtual Uyeler Uyeler { get; set; }
    }
}
