//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOTKayit
    {
        public int islem_no { get; set; }
        public int kullanici_no { get; set; }
        public int coin_no { get; set; }
        public string coin_miktar { get; set; }
    
        public virtual CoinList CoinList { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
