//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberler
    {
        public int Haber_No { get; set; }
        public string Haber_Baslik { get; set; }
        public string Haber_Gorsel { get; set; }
        public string Haber_Metin { get; set; }
    }
}
