//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemKayitlari
    {
        public int islem_no { get; set; }
        public Nullable<int> kullanici_no { get; set; }
        public Nullable<int> coin_no { get; set; }
        public Nullable<int> coin_deger { get; set; }
        public Nullable<System.DateTime> islem_tarih { get; set; }
        public Nullable<int> kazanc { get; set; }
    
        public virtual CoinList CoinList { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
