//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.ADAKayit = new HashSet<ADAKayit>();
            this.ADASohbet = new HashSet<ADASohbet>();
            this.BNBKayit = new HashSet<BNBKayit>();
            this.BNBSohbet = new HashSet<BNBSohbet>();
            this.BTCKayit = new HashSet<BTCKayit>();
            this.BTCSohbet = new HashSet<BTCSohbet>();
            this.DOTKayit = new HashSet<DOTKayit>();
            this.ETHKayit = new HashSet<ETHKayit>();
            this.islemKayitlari = new HashSet<islemKayitlari>();
            this.ETHSohbet = new HashSet<ETHSohbet>();
        }
    
        public int Kullanici_No { get; set; }
        public string Kullanici_Nick { get; set; }
        public string Kullanici_Ad { get; set; }
        public string Kullanici_Soyad { get; set; }
        public string e_posta { get; set; }
        public string profilfot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADAKayit> ADAKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADASohbet> ADASohbet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BNBKayit> BNBKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BNBSohbet> BNBSohbet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BTCKayit> BTCKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BTCSohbet> BTCSohbet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOTKayit> DOTKayit { get; set; }
        public virtual DOTSohbet DOTSohbet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETHKayit> ETHKayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islemKayitlari> islemKayitlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETHSohbet> ETHSohbet { get; set; }
    }
}
