//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebProjeDBEntities : DbContext
    {
        public WebProjeDBEntities()
            : base("name=WebProjeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADAKayit> ADAKayit { get; set; }
        public virtual DbSet<ADASohbet> ADASohbet { get; set; }
        public virtual DbSet<BNBKayit> BNBKayit { get; set; }
        public virtual DbSet<BNBSohbet> BNBSohbet { get; set; }
        public virtual DbSet<BTCKayit> BTCKayit { get; set; }
        public virtual DbSet<BTCSohbet> BTCSohbet { get; set; }
        public virtual DbSet<CoinDeger> CoinDeger { get; set; }
        public virtual DbSet<CoinList> CoinList { get; set; }
        public virtual DbSet<DOTKayit> DOTKayit { get; set; }
        public virtual DbSet<DOTSohbet> DOTSohbet { get; set; }
        public virtual DbSet<ETHKayit> ETHKayit { get; set; }
        public virtual DbSet<Haberler> Haberler { get; set; }
        public virtual DbSet<islemKayitlari> islemKayitlari { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
        public virtual DbSet<ETHSohbet> ETHSohbet { get; set; }
    }
}
